[CmdletBinding()]
param(
    [string]$ServerName = 'hypermesh-cae-agent',
    [string]$PythonExecutable,
    [string]$HyperMeshBatchExe,
    [string]$HyperMeshGuiExe,
    [string]$NastranTemplateDir,
    [string]$RunsDirectory,
    [string]$StateDirectory,
    [switch]$AsJson
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function ConvertTo-TomlBasicString {
    param([Parameter(Mandatory = $true)][string]$Value)

    $escaped = $Value.Replace('\', '\\').Replace('"', '\"')
    return '"' + $escaped + '"'
}

function Get-ConfigValue {
    param(
        $Config,
        [Parameter(Mandatory = $true)][string]$Name
    )

    if ($null -eq $Config) {
        return $null
    }
    $property = $Config.PSObject.Properties[$Name]
    if ($null -eq $property -or [string]::IsNullOrWhiteSpace([string]$property.Value)) {
        return $null
    }
    return [string]$property.Value
}

function Get-ExistingPath {
    param([string]$Value)

    if ([string]::IsNullOrWhiteSpace($Value) -or -not (Test-Path -LiteralPath $Value -PathType Leaf)) {
        return $null
    }
    return (Resolve-Path -LiteralPath $Value).Path
}

function Get-ExistingDirectory {
    param([string]$Value)

    if ([string]::IsNullOrWhiteSpace($Value) -or -not (Test-Path -LiteralPath $Value -PathType Container)) {
        return $null
    }
    return (Resolve-Path -LiteralPath $Value).Path
}

$pluginRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$launcher = Join-Path $pluginRoot 'scripts\start-hypermesh-mcp.ps1'
$requirements = Join-Path $pluginRoot 'requirements.txt'
if ([string]::IsNullOrWhiteSpace($StateDirectory)) {
    $StateDirectory = Join-Path $pluginRoot '.local'
}
$configPath = Join-Path ([System.IO.Path]::GetFullPath($StateDirectory)) 'workstation.json'
$workstation = $null
if (Test-Path -LiteralPath $configPath -PathType Leaf) {
    try {
        $workstation = Get-Content -LiteralPath $configPath -Raw | ConvertFrom-Json -ErrorAction Stop
    }
    catch {
        $workstation = $null
    }
}

$venvPython = Join-Path $pluginRoot '.venv\Scripts\python.exe'
if ([string]::IsNullOrWhiteSpace($PythonExecutable)) {
    if (Test-Path -LiteralPath $venvPython -PathType Leaf) {
        $PythonExecutable = (Resolve-Path -LiteralPath $venvPython).Path
    }
}
if ([string]::IsNullOrWhiteSpace($HyperMeshBatchExe)) {
    $HyperMeshBatchExe = Get-ConfigValue -Config $workstation -Name 'hypermesh_batch_exe'
    if ([string]::IsNullOrWhiteSpace($HyperMeshBatchExe)) {
        $HyperMeshBatchExe = [Environment]::GetEnvironmentVariable('HYPERMESH_BATCH_EXE', 'Process')
    }
}
if ([string]::IsNullOrWhiteSpace($HyperMeshGuiExe)) {
    $HyperMeshGuiExe = Get-ConfigValue -Config $workstation -Name 'hypermesh_gui_exe'
    if ([string]::IsNullOrWhiteSpace($HyperMeshGuiExe)) {
        $HyperMeshGuiExe = [Environment]::GetEnvironmentVariable('HYPERMESH_GUI_EXE', 'Process')
    }
}
if ([string]::IsNullOrWhiteSpace($RunsDirectory)) {
    $RunsDirectory = Get-ConfigValue -Config $workstation -Name 'runs_directory'
    if ([string]::IsNullOrWhiteSpace($RunsDirectory)) {
        $RunsDirectory = [Environment]::GetEnvironmentVariable('HYPERMESH_CAE_AGENT_RUNS_DIR', 'Process')
    }
}
if ([string]::IsNullOrWhiteSpace($NastranTemplateDir)) {
    $NastranTemplateDir = Get-ConfigValue -Config $workstation -Name 'nastran_template_dir'
    if ([string]::IsNullOrWhiteSpace($NastranTemplateDir)) {
        $NastranTemplateDir = [Environment]::GetEnvironmentVariable('HYPERMESH_NASTRAN_TEMPLATE_DIR', 'Process')
    }
}

$pythonCommand = if ([string]::IsNullOrWhiteSpace($PythonExecutable)) {
    $null
}
else {
    Get-Command $PythonExecutable -ErrorAction SilentlyContinue
}
$pythonPath = if ($pythonCommand) { $pythonCommand.Source } else { $null }
$batchPath = Get-ExistingPath -Value $HyperMeshBatchExe
$guiPath = Get-ExistingPath -Value $HyperMeshGuiExe
$nastranTemplatePath = Get-ExistingDirectory -Value $NastranTemplateDir
$mcpArgs = @('-NoLogo', '-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $launcher)
$tomlArgs = ($mcpArgs | ForEach-Object { ConvertTo-TomlBasicString $_ }) -join ', '
$tomlLines = @(
    '# Generated by create-codex-mcp-snippet.ps1. Paste into %USERPROFILE%\.codex\config.toml.',
    "[mcp_servers.$ServerName]",
    "command = $(ConvertTo-TomlBasicString 'powershell.exe')",
    "args = [$tomlArgs]",
    "cwd = $(ConvertTo-TomlBasicString $pluginRoot)",
    '',
    "[mcp_servers.$ServerName.env]"
)
if ($pythonPath) {
    $tomlLines += "PYTHON_EXECUTABLE = $(ConvertTo-TomlBasicString $pythonPath)"
}
if ($batchPath) {
    $tomlLines += "HYPERMESH_BATCH_EXE = $(ConvertTo-TomlBasicString $batchPath)"
}
if ($guiPath) {
    $tomlLines += "HYPERMESH_GUI_EXE = $(ConvertTo-TomlBasicString $guiPath)"
}
if ($nastranTemplatePath) {
    $tomlLines += "HYPERMESH_NASTRAN_TEMPLATE_DIR = $(ConvertTo-TomlBasicString $nastranTemplatePath)"
}
if (-not [string]::IsNullOrWhiteSpace($RunsDirectory)) {
    $tomlLines += "HYPERMESH_CAE_AGENT_RUNS_DIR = $(ConvertTo-TomlBasicString ([System.IO.Path]::GetFullPath($RunsDirectory)))"
}
$tomlSnippet = $tomlLines -join [Environment]::NewLine

$checks = [ordered]@{
    launcher = Test-Path -LiteralPath $launcher -PathType Leaf
    requirements = Test-Path -LiteralPath $requirements -PathType Leaf
    python = $null -ne $pythonPath
    batch_exe = $null -ne $batchPath
    gui_exe = $null -ne $guiPath
    nastran_template_dir = $null -ne $nastranTemplatePath
}
$ready = $checks.launcher -and $checks.requirements -and $checks.python -and ($checks.batch_exe -or $checks.gui_exe)
$result = [ordered]@{
    plugin_root = $pluginRoot
    launcher = $launcher
    requirements = $requirements
    python_executable = $pythonPath
    hypermesh_batch_exe = $batchPath
    hypermesh_gui_exe = $guiPath
    nastran_template_dir = $nastranTemplatePath
    checks = $checks
    ready_to_register = $ready
    next_action = if ($ready) {
        'Paste the TOML block into the target Codex configuration, then restart Codex.'
    }
    elseif (-not $checks.python) {
        'Create the package .venv with scripts/install-local.ps1 or provide -PythonExecutable.'
    }
    else {
        'Provide at least one valid local HyperMesh GUI or batch executable before registering the MCP.'
    }
    toml_snippet = $tomlSnippet
}

if ($AsJson) {
    $result | ConvertTo-Json -Depth 5
    exit 0
}
if (-not $ready) {
    $result | ConvertTo-Json -Depth 5
    exit 1
}
Write-Output $tomlSnippet
